swagger: "2.0"
info:
  title: 24i Movie API
  description: API description in Markdown.
  version: 1.0.0
host: localhost:9000
basePath: /
schemes:
  - http
paths:
  /api-docs:
    get:
      summary: Returns swagger documentation.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /movies:
    get:
      summary: Returns swagger documentation.
      description: Accepts an optional query id to get a single movie.
      query: id
      produces:
        - application/json
      responses:
        200:
          description: OK

  /populate:
    post:
      summary: Populates the db with seed data.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK